// <auto-generated />
using System;
using AkilliFiyatWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MyPortfolyoWebSite.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240520200226_InitialCreate22")]
    partial class InitialCreate22
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AkilliFiyatWeb.Entity.All_Products", b =>
                {
                    b.Property<int>("All_ProductsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("All_ProductsId"));

                    b.Property<string>("AyrintiLink")
                        .HasColumnType("longtext");

                    b.Property<double?>("Benzerlik")
                        .HasColumnType("double");

                    b.Property<string>("EskiFiyat")
                        .HasColumnType("longtext");

                    b.Property<string>("Fiyat")
                        .HasColumnType("longtext");

                    b.Property<double?>("IndirimOran")
                        .HasColumnType("double");

                    b.Property<string>("MarketAdi")
                        .HasColumnType("longtext");

                    b.Property<string>("MarketResmi")
                        .HasColumnType("longtext");

                    b.Property<int>("Miktar")
                        .HasColumnType("int");

                    b.Property<string>("UrunAdi")
                        .HasColumnType("longtext");

                    b.Property<string>("UrunResmi")
                        .HasColumnType("longtext");

                    b.HasKey("All_ProductsId");

                    b.ToTable("All_Products");
                });

            modelBuilder.Entity("AkilliFiyatWeb.Entity.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Exception")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("AkilliFiyatWeb.Entity.Urunler", b =>
                {
                    b.Property<int>("UrunlerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UrunlerId"));

                    b.Property<string>("AyrintiLink")
                        .HasColumnType("longtext");

                    b.Property<double?>("Benzerlik")
                        .HasColumnType("double");

                    b.Property<string>("EskiFiyat")
                        .HasColumnType("longtext");

                    b.Property<string>("Fiyat")
                        .HasColumnType("longtext");

                    b.Property<double?>("IndirimOran")
                        .HasColumnType("double");

                    b.Property<string>("MarketAdi")
                        .HasColumnType("longtext");

                    b.Property<string>("MarketResmi")
                        .HasColumnType("longtext");

                    b.Property<int>("Miktar")
                        .HasColumnType("int");

                    b.Property<string>("UrunAdi")
                        .HasColumnType("longtext");

                    b.Property<string>("UrunResmi")
                        .HasColumnType("longtext");

                    b.HasKey("UrunlerId");

                    b.ToTable("Urunler");
                });
#pragma warning restore 612, 618
        }
    }
}
